language: scala

before_script:
    - sbt script

scala:
    - 2.11.2
jdk:
    - oraclejdk7

branches:
    only:
        - master

notifications:
    email:
        - ekneuss@gmail.com
        - philippe.suter@gmail.com
    irc: "chat.freenode.net#epfl-lara"
